spring.application.name=mobile-app
spring.datasource.username=harsh
spring.datasource.password=user@123
spring.datasource.url=jdbc:mysql://localhost:3306/photo_app
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.springframework.security=OFF
logging.level.com.mobileapp=OFF
logging.level.com.mobileapp.security=OFF